import Head from "next/head";
import SearchPage from "@/components/SearchPage";
import localFont from "next/font/local";

// const spFont = localFont({
//   src: "nasin-nanpa.otf",
//   declarations: [{ prop: "unicode-range", value: "U+F1900-F19FF" }],
// });
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className={spFont.className}> */}
      <SearchPage></SearchPage>
      {/* </div> */}
    </>
  );
}
